# _config.yml

title: "MiniMotive"
description: "Пишу как собираю модели"
baseurl: "" # для github.io
url: "https://vasiliy-mazaev.github.io"

theme: minima
plugins:
  - jekyll-feed

lang: ru

collections:
  articles:
    output: true
    permalink: /articles/:path/
