# _config.yml

title: "MiniMotive"
description: "Всегда собирал модели, теперь решил еще и писать об этом заметки в сети."
baseurl: "" # для github.io
url: "https://vasiliy-mazaev.github.io"
email: vasiliy.mazaev@yandex.ru

theme: minima
plugins:
  - jekyll-feed

lang: ru

collections:
  articles:
    output: true
    permalink: /articles/:path/
